alrm = (
    ('None', '-'),
    ('Уставки', (
        ('Cutout', 'Cutout'),
        ('r23', 'Уставка компрессоров централи'),
        ('r28', 'Уставка конденсаторов централи'),
        ('r12', 'Основной выключатель'),
        ('A03-alarm-delay', 'А03. Задержка аварийного сигнала по температуре'),
        ('A13-high-lim-air', 'А13. Верхний предел по температуре'),
    )
     ),
    ('Потребители', (
        ('E1', 'E1. Неисправность контроллера'),
        ('E6', 'E6. Замена элементов питания и проверка времени'),
        ('E19', 'Е19. Входной сигнал на клеммах за пределами температуры'),
        ('E20', 'Е20. Неисправность датчика давления'),
        ('E23', 'Е23. Неисправность датчика температуры S1'),
        ('E24', 'Е24. Неисправность датчика температуры S2'),
        ('E25', 'Е25. Неисправность датчика температуры S3'),
        ('E26', 'Е26. Неисправность датчика температуры S4'),
        ('E27', 'Е27. Неисправность датчика температуры S5'),
        ('E28', 'Е28. Неисправность датчика температуры S6'),
        ('E29', 'Е29. Неисправность датчика температуры в объеме (Sair)'),
        ('E34', 'Е34. Неисправность датчика температуры S3B'),
        ('E37', 'Е37. Неисправность датчика температуры S5B'),
        ('E57', 'Е57. RH input err'),
        ('A1', 'A1. Высокая температура'),
        ('A2', 'A2. Низкая температура'),
        ('A4', 'A4. Дверь открыта'),
        ('A5', 'А5. При координированном оттаивании сработала задержка о16'),
        ('A10', 'А10. Проблема со впрыском'),
        ('A11', 'А11. Не выбран хладагент'),
        ('A13', 'А13. Высокая температура по датчику S6'),
        ('A14', 'А14. Низкая температура по датчику S6'),
        ('A15', 'А15. Вход DI1'),
        ('A16', 'А16. Вход DI2'),
        ('A43', 'А43. Проверить питание на шаговом двигателе'),
        ('A45', 'А45. Дежурный режим'),
        ('A59', 'А59. Уборка по сигналй цифрового входа'),
        ('A71', 'A71. Низкая температура секция B'),
        ('A70', 'A70. Высокая температура секция B'),
        ('A74', 'А74. Сбой адаптивной функции оттаивания'),
        ('A75', 'А75. Испаритель покрыт инеем. Понижение расхода воздуха'),
        ('A76', 'А76. Оттаивание испарителя прошло неудовлетворительно'),
        ('max-def-time', 'max def time'),
        ('---Refg-Leak', '---Refg Leak'),
        ('---AD-flashgas', '---AD flashgas'),
        ('AA2', 'AA2. Refg Leak'),
        ('AA3', 'AA3. CO2 Alarm'),
        ('a02', 'a02. HighHumidity'),
        ('a03', 'a03. LowHumidity'),
        ('a04', 'a04. Wrong IO cfg'),
        ('E2', 'E2. Disconnected room sensor'),
        ('E3', 'E3. Short - circuited room sensor'),
        ('E4', 'E4. Disconnected defrost sensor'),
        ('E5', 'E5. Short - circuited defrost sensor'),
    )
     ),
    ('Централи', (
        ('central', 'Параметры o75 DO9 Function, Ext_ Main Switch'),
        ('c_A17_531', 'Высокое давление конденсации 531'),
        ('c_A17_551', 'Высокое давление конденсации 551'),
        ('c_Е1', 'Е1. Неисправность контроллера централи'),
        ('c_Е2', 'Е2. Неисправность датчиков давления'),
        ('c_А2', 'А2. Низкая температура кипения'),
        ('c_А11', 'А11. Не выбран тип хладагента'),
        ('c_А45', 'А45. Режим ожидания'),
        ('c_A34', 'A34. Авария вентиляторов'),
        ('c_А28', 'А28. Внешний аварийный сигнал вход №1'),
        ('c_А29', 'А29. Внешний аварийный сигнал вход №2'),
        ('c_А30', 'А30. Внешний аварийный сигнал вход №3'),
        ('c_А31', 'А31. Внешний аварийный сигнал вход №4'),
        ('c_А32', 'А32. Внешний аварийный сигнал вход №5'),
        ('c1', 'Compressor 1A safety cut out'),
        ('c1_351', 'Compressor 1 safety cut out'),
        ('c1_531', 'А19. Авария компрессора №1'),
        ('c2', 'Compressor 2A safety cut out'),
        ('c2_351', 'Compressor 2 safety cut out'),
        ('c2_531', 'А20. Авария компрессора №2'),
        ('c3', 'Compressor 3A safety cut out'),
        ('c3_351', 'Compressor 3 safety cut out'),
        ('c3_531', 'А21. Авария компрессора №3'),
        ('c4', 'Compressor 4A safety cut out'),
        ('c4_351', 'Compressor 4 safety cut out'),
        ('c4_531', 'А22. Авария компрессора №4'),
        ('c5', 'Compressor 5A safety cut out'),
        ('c5_531', 'А23. Авария компрессора №5'),
        ('c6', 'Compressor 6A safety cut out'),
        ('c6_531', 'А24. Авария компрессора №6'),
        ('c7', 'Compressor 7A safety cut out'),
        ('c7_531', 'А25. Авария компрессора №7'),
        ('c8', 'Compressor 8A safety cut out'),
        ('c8_531', 'А26. Авария компрессора №8'),
        ('PoA_Low', 'PoA Low suction pressure'),
        ('Po_S4_Low', 'Po/S4 Low suction pressure'),
        ('PoA_High', 'PoA High suction pressure'),
        ('Po_S4_High', 'Po/S4 High suction pressure'),
        ('c_Standby', 'Standby mode'),
        ('c_Refr_not_selected', 'Refrigerant not selected'),
        ('Pc_se', 'Pc sensor error'),
        ('Output_in_manual_mode', 'Output in manual mode'),
        ('C1A_Hdt', 'Comp_ 1A High disch_ temp'),
        ('C1_Hdt', 'Comp_ 1 High disch_ temp'),
        ('PoA_se', 'PoA sensor error'),
        ('Po_se', 'Po sensor error'),
        ('LP_A_ssco', 'LP A safety switch cut out'),
        ('LP_ssco', 'LP safety switch cut out'),
        ('SdA_Hdt', 'SdA High discharge temp'),
        ('SsA_Ls', 'SsA Low superheat'),
        ('SdA_se', 'SdA sensor error'),
        ('Sd_C1A_se', 'Sd Comp_ 1A sensor error'),
        ('Sd_C1_se', 'Sd Comp_ 1 sensor error'),
        ('fan_sco', 'Common fan safety cut out'),
        ('HP_ssc', 'HP safety switch cutout'),
        ('SsA_se', 'SsA sensor error'),
        ('S4A_se', 'S4A sensor error'),
        ('S4_se', 'S4 sensor error'),
        ('SsA_Hs', 'SsA High superheat'),
        ('f1', 'Fan 1 safety cut out'),
        ('f2', 'Fan 2 safety cut out'),
        ('f3', 'Fan 3 safety cut out'),
        ('f4', 'Fan 4 safety cut out'),
        ('f5', 'Fan 5 safety cut out'),
        ('f6', 'Fan 6 safety cut out'),
        ('f7', 'Fan 7 safety cut out'),
        ('f8', 'Fan 8 safety cut out'),
        ('Sс3_se', 'Sс3 sensor error'),
        ('Saux', 'Saux error'),
        ('S7_se', 'S7 sensor error'),
        ('IO_CE', 'IO Configuration Error'),
        ('GA1-1', 'GA1 - Low temperature alarm'),
        ('GA1-2', 'GA1 - Oil level alarm'),
        ('GA1-3', 'GA1 - Oil temperature alarm'),
        ('GA1-4', 'GA1 - Liquid level alarm'),
        ('GA1-5', 'GA1 - Leak detection alarm'),
        ('GA1-6', 'GA1 - Inverter fault'),
        ('GA1-7', 'GA1 - General alarm'),
        ('GA1-8', 'GA1 - High pressure alarm'),
        ('GA1-9', 'GA1 - Low pressure alarm'),
        ('GA1-10', 'GA1 - High temperature alarm'),
        ('GA1-11', 'GA1 - Brine Pressure Alarm'),
        ('GA1-12', 'GA1 - Dry Cooler Alarm'),
        ('GA1-13', 'GA1 - Pump Alarm'),
        ('GA1-14', 'GA1 - Motor Prot Compr Alarm'),
        ('GA2-1', 'GA2 - Low temperature alarm'),
        ('GA2-2', 'GA2 - High temperature alarm'),
        ('GA2-3', 'GA2 - Low pressure alarm'),
        ('GA2-4', 'GA2 - High pressure alarm'),
        ('GA2-5', 'GA2 - General alarm'),
        ('GA2-6', 'GA2 - Oil level alarm'),
        ('GA2-7', 'GA2 - Oil temperature alarm'),
        ('GA2-8', 'GA2 - Liquid level alarm'),
        ('GA2-9', 'GA2 - Leak detection alarm'),
        ('GA2-10', 'GA2 - Inverter fault'),
        ('GA2-11', 'GA2 - Motor Prot Compr Alarm'),
        ('GA2-12', 'GA2 - Brine Pressure Alarm'),
        ('GA2-13', 'GA2 - Dry Cooler Alarm'),
        ('GA2-14', 'GA2 - Pump Alarm'),
        ('GA3-1', 'GA3 - Inverter fault'),
        ('GA3-2', 'GA3 - Leak detection alarm'),
        ('GA3-3', 'GA3 - Liquid level alarm'),
        ('GA3-4', 'GA3 - Oil temperature alarm'),
        ('GA3-5', 'GA3 - Oil level alarm'),
        ('GA3-6', 'GA3 - Low temperature alarm'),
        ('GA3-7', 'GA3 - High temperature alarm'),
        ('GA3-8', 'GA3 - General alarm'),
        ('GA3-9', 'GA3 - High pressure alarm'),
        ('GA3-10', 'GA3 - Low pressure alarm'),
        ('GA3-11', 'GA3 - Motor Prot Compr Alarm'),
        ('GA3-12', 'GA3 - Brine Pressure Alarm'),
        ('GA3-13', 'GA3 - Dry Cooler Alarm'),
        ('GA3-14', 'GA3 - Pump Alarm'),
    )
     ),
)

stations = (
    ('4', 'SCADA-XO'),
    ('10', 'SCADA-XO2'),
    ('11', 'SCADA-XO3'),
    ('34', 'SCADA-XO4'),
    ('35', 'SCADA-XO5'),
)
