nfb = ["noffl 1",
       "noffl 2",
       "noffl 3",
       "noffl 4",
       "noffl 5",
       "noffl 6",
       "noffl 7",
       "noffl 8",
       "noffl 9",
       "noffl 10",
       "noffl 11",
       "noffl 12",
       "noffl 13",
       "noffl 14",
       "noffl 15"]
