indices = {
    'alrm_code': 0,
    'alrm_text': 1,
    'group_name': 1,
    'group_alarms': 2,
    'empty_group_len': 4,
    'contr_name': 0,
    'xo_type': 0,
    'product': 1,
    'alarm_index': 0,
    'alarm_id': 0,
    'full_name': 2,
    'station_id': 0,
    'passport_type': 1,
    'group_id': 2,
    'passport_id': 3,
    'value_type': 4,
    'groups_index': 37,
    'grp_name': 0,
    'own_config': 1,
    'params': 2,
    'zone': 0,
    'parid': 1,
    'stid': 2,
    'type': 3,
    'grid': 4,
    'psid': 5,
    'valtype': 6,
    'typename': 7,
    'cipher': 8,
    'klogger_name': 9,
    'usepreagr': 10,
    'module': 1,
    'first_tag': 1,
    'first_contr': 3,
    'first_fb_input': 1,
    'settings': 0,
    'name': 0,
    'alarm_split': 1,
}


def get_index(index_name: str) -> int:
    return indices[index_name]
