template_tags = {
    '531': [
        'r23 Po Set Point',
        'r25 Po Ref Max',
        'r13 Night offset',
        'r04 Adjust Sensor',
        'r29 Pc Ref',
        'u44 Sc3 Temp',
        'r28 Pc Set Point',
        '--- EKC State',
        'r32 Adjust Sensor',
        'A03 Alarm Delay',
        'A11 Min Po',
        'A30 Max Pc',
        '--- Ошибка EKC',
        'o30 Refrigerant',
        'o75 DO9 Function',
        'E1 Ctrl Fault',
        'E2 Out Of Range',
        'A02 Low Po Alarm',
        'A17 Hi Pc Alarm',
        'A11 No Rfg Sel',
        'A27 Высокая Saux1',
        'A28 DI1 Alarm',
        'A29 DI2 Alarm',
        'A30 DI3 Alarm',
        'A31 DI4 Alarm',
        'A32 DI5 Alarm',
        'A45 Standby Mode',
        'A34 Fan Fault',
        'A19 Comp 1 Fault',
        'A20 Comp 2 Fault',
        'A21 Comp 3 Fault',
        'A22 Comp 4 Fault',
        'A23 Comp 5 Fault',
        'A24 Comp 6 Fault',
        'A25 Comp 7 Fault',
        'A26 Comp 8 Fault',
        '--- Fan Cap %',
        '--- Comp Cap %',
        'r12 Main Switch',
        'r57 Po',
        '--- Pc'
    ],
    '202B': [
        '--- Cutout',
        'r01 Differential',
        'r04 Disp Adj K',
        'r09 Adjust Sair',
        'r12 Main Switch',
        'r13 Night offset',
        'A03 Alarm Delay',
        'A13 High Lim Air',
        '--- EKC State',
        'u69 Sair Temp',
        'u09 S5 Temp',
        'u13 Night Cond',
        'u58 Comp1',
        'u60 Def Relay',
        'u59 Fan Relay',
        '--- Ошибка EKC',
        '--- EKC Error_2',
        '--- RTC Error',
        '--- Sair Error',
        '--- S5 Error',
        '--- High Temp Alarm',
        '--- Low Temp Alarm',
        '--- Door Alarm',
        '--- DI1 Alarm',
        '--- Конд Авария',
        '--- Max Def Time',
        '--- Max Hold Time',
        '--- Case Clean',
        '--- Standby Mode'
    ],
    '55': [
        'u00 Ctrl_ state',
        'u17 Ther Air',
        'u26 Evap Temp Te',
        'u20 S2 Temp',
        'u12 S3 Air Temp',
        'u16 S4 Air Temp',
        'u09 S5 Temp',
        'u23 AKV OD %',
        'r12 Main Switch',
        'o30 Refrigerant',
        'u13 Night Cond',
        'r00 Cutout',
        'r01 Differential',
        'r15 Ther S4 %',
        'r13 Night offset',
        'A13 High Lim Air',
        'A03 Alarm Delay',
        'u21 Superheat',
        'u22 Superheat Ref',
        'u11 Defrost Time',
        'r04 Disp Adj K',
        'r10 Adjust S3',
        'r09 Adjust S4',
        'u25 Evap Press Pe',
        'u58 Comp1',
        'u59 Fan Relay',
        'u60 Def Relay',
        '--- Ctrl Fault',
        '--- RTC Error',
        '--- Pe Error',
        '--- S2 Error',
        '--- S3 Error',
        '--- S4 Error',
        '--- S5 Error',
        '--- High Temp Alarm',
        '--- Low Temp Alarm',
        '--- Door Alarm',
        '--- Max Hold Time',
        '--- No Rfg Sel',
        '--- DI1 Alarm',
        '--- DI2 Alarm',
        '--- Standby Mode',
        '--- Case Clean',
        '--- CO2 Alarm',
        '--- Refrigerant leak',
        '--- Wrong IO cfg',
        '--- Max Def Time',
        '--- Cutout'
    ],
    '202D': [
        '--- Cutout',
        'r01 Differential',
        'r04 Disp Adj K',
        'r09 Adjust S4',
        'r10 Adjust S3',
        'r12 Main Switch',
        'r13 Night offset',
        'r15 Ther S4 %',
        'A03 Alarm Delay',
        'A13 High Lim Air',
        '--- EKC State',
        'u17 Ther Air',
        'u12 S3 Air Temp',
        'u16 S4 Air Temp',
        'u09 S5 Temp',
        'u13 Night Cond',
        'u58 Comp1',
        'u60 Def Relay',
        'u59 Fan Relay',
        '--- Ошибка EKC',
        '--- EKC Error_2',
        '--- RTC Error',
        '--- S3 Error',
        '--- S4 Error',
        '--- S5 Error',
        '--- High Temp Alarm',
        '--- Low Temp Alarm',
        '--- Door Alarm',
        '--- DI1 Alarm',
        '--- DI2 Alarm',
        '--- Max Def Time',
        '--- Max Hold Time',
        '--- Case Clean',
        '--- Standby Mode'
    ],
    '202B Cutout Temp': [],
    '550': [],
    '551': [],
    '351': []
}
